language: python
dist: xenial

env:
  global:
  - BIN_NAME=$(git describe --tags --dirty --always)
  - CONST_VAR="binNameTest"

addons:
  artifacts:
    paths:
      - ./dist/mac
      - ./dist/win
    target_paths:
      - ${TRAVIS_BUILD_NUMBER}
    debug: true

matrix:
  include:
    - os: osx
      language: sh
      python: "3.6"
      before_install:
        - brew update
        - brew install unix2dos
        - pip3 install pyinstaller wxpython pyxform
      script:
        - ./make-mac.sh
        - ./make-dist.sh
        # This line is what renames the file to include the git hash.
        - mv ./dist/mac/ODK-XLSForm-Offline-macOS.zip ./dist/mac/ODK-XLSForm-Offline-macOS-${CONST_VAR}.zip
        - echo "TESTING VAR NAMES"
        - echo ${BIN_NAME}
        - echo ${CONST_VAR}
    - os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - pip3 install pyinstaller
        - pip3 install pyxform
      script:
        - ./make-win.bat

cache: pip
