language: python
dist: xenial

env:
  global:
  - BIN_NAME=$(git describe --tags --dirty --always)

addons:
  artifacts:
    paths:
      - ./dist/mac/ODK-XLSForm-Offline-macOS-${BIN_NAME}.zip
      - ./dist/win
    target_paths:
      - ${TRAVIS_BUILD_NUMBER}
    debug: true

matrix:
  include:
    - os: osx
      language: sh
      python: "3.6"
      before_install:
        - brew update
        - brew install unix2dos
        - pip3 install pyinstaller wxpython pyxform
      script:
        - ./make-mac.sh
        - ./make-dist.sh
        - mv ./dist/mac/ODK-XLSForm-Offline-macOS.zip ./dist/mac/ODK-XLSForm-Offline-macOS-${BIN_NAME}.zip
    - os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - pip3 install pyinstaller
        - pip3 install pyxform
      script:
        - ./make-win.bat

cache: pip
